#!/bin/sh
#
# @name Gazebo Piazinho mono cam
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=piazinho_mono_cam}

. ${R}etc/init.d-posix/airframes/6767_gz_piazinho

param set-default SYS_AUTOSTART 6768
