#!/bin/sh
#
# @name Gazebo Piazinho mono cam
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=piazinho_mid360_cam}

. ${R}etc/init.d-posix/airframes/6969_gz_piazinho


param set-default SENS_EN_GPSSIM 0
param set-default SYS_HAS_GPS 0
param set-default EKF2_EV_CTRL 15

