#!/bin/sh
#
# @name Gazebo CoisaRuim Mid360 Range Cam
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=coisaruim_mid360-0_range_cam}

. ${R}etc/init.d-posix/airframes/6973_gz_coisaruim

param set-default SYS_AUTOSTART 6978
param set-default SYS_HAS_NUM_DIST 1

param set-default EKF2_OF_CTRL 0
param set-default SENS_FLOW_MINHGT 0.08
param set-default SENS_FLOW_MAXHGT 8.0

param set-default SENS_EN_GPSSIM 0 #0
param set-default SYS_HAS_GPS 0 #0
param set-default SYS_HAS_BARO 0
param set-default EKF2_EV_CTRL 9 # 9
param set-default EKF2_GPS_CTRL 0 #0
param set-default EKF2_RNG_CTRL 2

param set-default EKF2_EV_DELAY 200
# External vision is already transformed to the vehicle body origin by odom_to_px4.
param set-default EKF2_EV_POS_X 0
param set-default EKF2_EV_POS_Y 0
param set-default EKF2_EV_POS_Z 0

param set-default MC_PITCHRATE_K 2.45
param set-default MC_PITCHRATE_D 0.0018
param set-default MC_PITCHRATE_I 0.175

param set-default MC_ROLLRATE_K 2.45
param set-default MC_ROLLRATE_D 0.0018
param set-default MC_ROLLRATE_I 0.175

param set-default MC_YAWRATE_K 3.0
param set-default MC_YAWRATE_I 0.22

param set-default MC_ROLL_P 14.0
param set-default MC_PITCH_P 14.0

param set-default MPC_XY_VEL_P_ACC 1.8
param set-default MPC_XY_VEL_I_ACC 0.4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default MPC_Z_VEL_P_ACC 7.0
param set-default MPC_Z_VEL_I_ACC 2.4
param set-default MPC_Z_VEL_D_ACC 0.0








param set-default EKF2_DELAY_MAX 300
param set-default EKF2_BARO_CTRL 0
param set-default EKF2_AGP_CTRL 0
param set-default EKF2_HGT_REF 2

if param compare -s SYS_HAS_NUM_DIST 1
then
    sensor_rangefinder_sim start
fi

