#!/bin/sh
#
# @name Piazinho Gralhabots
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Carlos Zanon
#

. ${R}etc/init.d/rc.mc_defaults

param set-default BAT1_A_PER_V 36.367515563964844
param set-default BAT1_N_CELLS 4
param set-default BAT1_V_DIV 18.100000381469727

param set-default CBRK_IO_SAFETY 0

param set-default COM_FLTMODE1 1
param set-default COM_FLTMODE2 2
param set-default COM_FLTMODE3 8
param set-default COM_FLTMODE4 5
param set-default COM_FLTMODE5 11
param set-default COM_FLTMODE6 11

param set-default COM_RC_IN_MODE 2
param set-default COM_RC_OVERRIDE 3

param set-default EKF2_GPS_POS_X 0.1
param set-default EKF2_GPS_POS_Z -0.1

param set-default EKF2_HGT_REF 2
param set-default EKF2_MIN_RNG 0.17

param set-default EKF2_IMU_POS_X 0.05
param set-default EKF2_IMU_POS_Z -0.05

param set-default EKF2_OF_CTRL 1
param set-default EKF2_OF_POS_X 0.1
param set-default EKF2_OF_POS_Z 0.03

param set-default EKF2_RNG_CTRL 2
param set-default EKF2_RNG_NOISE 0.02
param set-default EKF2_RNG_POS_X 0.1
param set-default EKF2_RNG_POS_Z 0.03

param set-default MAV_0_CONFIG 103
param set-default MAV_0_MODE 5
param set-default MAV_0_RATE 0
param set-default MAV_2_CONFIG 101
param set-default MAV_TYPE 2

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.16
param set-default CA_ROTOR0_PY 0.16
param set-default CA_ROTOR1_PX -0.16
param set-default CA_ROTOR1_PY -0.16
param set-default CA_ROTOR2_PX 0.16
param set-default CA_ROTOR2_PY -0.16
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.16
param set-default CA_ROTOR3_PY 0.16
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_DIS1 900
param set-default PWM_MAIN_DIS2 900
param set-default PWM_MAIN_DIS3 900
param set-default PWM_MAIN_DIS4 900

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default PWM_MAIN_MAX1 2200
param set-default PWM_MAIN_MAX2 2200
param set-default PWM_MAIN_MAX3 2200
param set-default PWM_MAIN_MAX4 2200

param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100

param set-default RC_CHAN_CNT 8
param set-default RC_MAP_ARM_SW 6
param set-default RC_MAP_FLTMODE 5
param set-default RC_MAP_KILL_SW 7
param set-default RC_MAP_OFFB_SW 8
param set-default RC_MAP_PITCH 2
param set-default RC_MAP_ROLL 4
param set-default RC_MAP_THROTTLE 3
param set-default RC_MAP_YAW 1

param set-default RTL_DESCEND_ALT 5.0
param set-default RTL_RETURN_ALT 3.0

param set-default SDLOG_MISSION 1
param set-default SDLOG_MODE 2
param set-default SDLOG_PROFILE 1279
param set-default SDLOG_UTC_OFFSET -180

param set-default SER_TEL1_BAUD 115200
param set-default SER_TEL2_BAUD 2000000
param set-default SER_TEL3_BAUD 921600

param set-default SYS_AUTOSTART 4067

param set-default USB_MAV_MODE 8
param set-default UXRCE_DDS_CFG 102
